version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "@lwc/*"
      - match:
          dependency_name: "@salesforce/*"
