name: validate pr
on:
  pull_request:
    branches: [main]

jobs:
  pr-validation:
    uses: salesforcecli/github-workflows/.github/workflows/validatePR.yml@main
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main